# This file was generated by GoReleaser. DO NOT EDIT.
cask "agent-local" do
  version "0.34.1"

  on_macos do
    sha256 "5840457d865b6a21db9e8779cbd83f9194383049e0ba041587b7d874a9345fec"
    url "https://github.com/jefrontv/agent-local/releases/download/v#{version}/agent-local_#{version}_darwin_universal.tar.gz"
  end

  name "agent-local"
  desc "Local WordPress for humans and agents — sites, PHP versions, MariaDB and branch previews from one binary"
  homepage "https://github.com/jefrontv/agent-local"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "agent-local"

  postflight do
    if OS.mac?
      system "xattr", "-dr", "com.apple.quarantine", "#{staged_path}/agent-local"
    end
  end

  uninstall launchctl: [
      "local.agent-local.front",
    ]

  zap trash: [
      "~/.agent-local",
    ]

  caveats <<~EOS
    agent-local installs the rest of the stack on demand:
      agent-local doctor --fix    # PHP, MariaDB, wp-cli as needed
      agent-local sudo            # one-time, removes every password prompt
      agent-local create mysite
    Root is used only for /etc/hosts entries and trusting local TLS certs.
  EOS
end
